In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("household_energy_consumption.csv")

In [3]:
df.head()

,Household_ID,Date,Energy_Consumption_kWh,Household_Size,Avg_Temperature_C,Has_AC,Peak_Hours_Usage_kWh
0,H00001,2025-04-01,8.4,4,17.8,No,3.2
1,H00001,2025-04-02,7.9,4,17.3,No,2.8
2,H00001,2025-04-03,9.2,4,18.6,No,3.0
3,H00001,2025-04-04,7.9,4,18.2,No,2.7
4,H00001,2025-04-05,9.6,4,11.9,No,3.2

In [4]:
df.shape

(90000, 7)

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 90000 entries, 0 to 89999
Data columns (total 7 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Household_ID            90000 non-null  object
 1   Date                    90000 non-null  object
 2   Energy_Consumption_kWh  90000 non-null  float64
 3   Household_Size          90000 non-null  int64
 4   Avg_Temperature_C       90000 non-null  float64
 5   Has_AC                  90000 non-null  object
 6   Peak_Hours_Usage_kWh    90000 non-null  float64
dtypes: float64(3), int64(1), object(3)
memory usage: 4.8+ MB

In [6]:
df.isnull().sum()

Household_ID              0
Date                      0
Energy_Consumption_kWh    0
Household_Size            0
Avg_Temperature_C         0
Has_AC                    0
Peak_Hours_Usage_kWh      0
dtype: int64

In [7]:
df.describe()

,Energy_Consumption_kWh,Household_Size,Avg_Temperature_C,Peak_Hours_Usage_kWh
count,90000.000000,90000.000000,90000.000000,90000.000000
mean,10.571988,3.487811,17.505802,4.319557
std,5.519494,1.709761,2.491621,2.531432
min,0.500000,1.000000,10.000000,0.200000
25%,6.000000,2.000000,15.800000,2.300000
50%,10.400000,3.000000,17.500000,4.000000
75%,14.800000,5.000000,19.200000,6.000000
max,20.000000,6.000000,25.000000,10.000000

In [11]:
df['Date'] = pd.to_datetime(df['Date'])

df['Month'] = df['Date'].dt.month
df['DayOfWeek'] = df['Date'].dt.dayofweek

df.drop(columns=['Date', 'Household_ID'], inplace=True)

In [12]:
df.head()

,Energy_Consumption_kWh,Household_Size,Avg_Temperature_C,Has_AC,Peak_Hours_Usage_kWh,Month,DayOfWeek
0,8.4,4,17.8,No,3.2,4,1
1,7.9,4,17.3,No,2.8,4,2
2,9.2,4,18.6,No,3.0,4,3
3,7.9,4,18.2,No,2.7,4,4
4,9.6,4,11.9,No,3.2,4,5

In [14]:
from pycaret.regression import setup, compare_models, tune_model, evaluate_model

In [15]:
s = setup(
    data=df,
    target='Energy_Consumption',
    session_id=42
)

ValueError: Invalid value for the target parameter. Column Energy_Consumption not found in the data.

In [16]:
print(df.columns)

Index(['Energy_Consumption_kWh', 'Household_Size', 'Avg_Temperature_C',
       'Has_AC', 'Peak_Hours_Usage_kWh', 'Month', 'DayOfWeek'],
      dtype='object')

In [17]:
s = setup(
    data=df,
    target='Energy_Consumption_kWh',
    session_id=42
)

In [18]:
best_model = compare_models()

In [19]:
tuned_model = tune_model(best_model)

Fitting 10 folds for each of 10 candidates, totalling 100 fits

In [20]:
evaluate_model(tuned_model)

interactive(children=(ToggleButtons(description='Plot Type:', icons=('',), options=(('Pipeline Plot', 'pipelin…

In [21]:
from pycaret.regression import predict_model

predictions = predict_model(tuned_model)

predictions.head()

,Household_Size,Avg_Temperature_C,Has_AC,Peak_Hours_Usage_kWh,Month,DayOfWeek,Energy_Consumption_kWh,prediction_label
89610,4,19.799999,Yes,6.5,4,4,13.7,14.749656
12456,2,13.200000,Yes,3.3,4,4,7.3,7.339322
53403,3,15.400000,Yes,5.7,4,1,13.0,12.218256
62905,4,19.200001,No,2.8,4,4,9.0,8.441805
66339,6,17.600000,No,6.4,4,1,17.0,16.908160